name: Python CI

on:
  push:
    branches:
      - main  # 这里可以根据你的主分支名称调整

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu Runner

    steps:
    - uses: actions/checkout@v2  # 检出你的仓库内容

    - name: Set up Python  # 设置 Python 环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 指定你的 Python 版本，比如 3.6、3.7 等

    - name: Install dependencies  # 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install DrissionPage

    - name: Run script  # 运行你的 Python 脚本
      run: python 1.py
