name: Python with Chrome

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify Google Chrome installation
      run: google-chrome --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install DrissionPage  # 或其他你需要的 Python 库

    - name: Run Python script
      run: python 1.py

    - name: Upload accounts.txt as artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: accounts
        path: accounts.txt
