name: Install ChromeDriver

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}/chromedriver_linux64.zip"
        unzip /tmp/chromedriver.zip -d /tmp
        sudo mv /tmp/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Verify ChromeDriver installation
      run: chromedriver --version

    - name: Run Python script
      run: |
        python -m pip install --upgrade pip
        pip install DrissionPage
        python 1.py

    - name: Upload accounts.txt as artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: accounts
        path: accounts.txt
